### ISSUE TITLE
pown or powi ?

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#68]
I wonder why you did not call the [`pown`](https://docs.rs/inari/latest/inari/struct.Interval.html#method.pown) function `powi` as in the [standard library](https://doc.rust-lang.org/std/primitive.f64.html#method.powi)?

**Comment by unageek** [comment]
I don't remember why I named it so, but I guess it was just because `pown` is the name used in the IEEE standards.

If we rename it, [`pow`](https://docs.rs/inari/latest/inari/struct.Interval.html#method.pow) should be renamed to `powf` as well. But I feel it uneasy, since it sounds like a function that returns a floating-point number instead of an interval.

**Comment by Chris00** [comment]
Not necessarily.  `pow` in `std` has the signature `pow(T, exp: u32) → T` and is implemented for integers only (for which negative or fractional powers do not make sense).  In my mind, `pow` is the “largest” exponentiation function for the type (and I do not know why they did not called `powf` simply `pow`).  The stdlib type of `powi(T, n: i32) → T` is the right one for the current `pown` function (with the name `pown`, you would think it only accepts powers ∈ ℕ).

(Now, one could also implement `pow(Interval, E) → Interval` as a trait and reuse the name for the two kinds of exponents. 😀)

**Comment by Chris00** [comment]
How about to implement the [`Pow`](https://docs.rs/num-traits/0.2.14/num_traits/pow/trait.Pow.html) trait?  This way, both functions may be called `pow`.

**Comment by unageek** [comment]
Yeah, but I want to keep their names different, since their semantics are different:

- pow(_x_, _y_) returns
  - exp(_y_ ln(_x_)) if _x_ > 0,
  - 0 if _x_ = 0 ∧ _y_ > 0.
- pown(_x_, _n_) returns
  - _x_<sup>_n_</sup> = _x_ × ⋯ × _x_ (_n_ times) if _n_ > 0,
  - 1 if _n_ = 0,
  - 1/x<sup>−n</sup> if _n_ < 0.

**Comment by unageek** [comment]
Anyway, renaming `pown` to `powi` sounds reasonable. Could you send a PR for that?
